# Generated by Django 4.2.7 on 2023-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0005_provenanceevent_level_alter_provenanceevent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provenanceevent",
            name="date",
            field=models.DateField(default=None, null=True),
        ),
    ]
