# Generated by Django 4.2.7 on 2023-11-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("artifacts", "0002_artifact_attribute_collection_date_materialtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="aw_item_number",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artifacts.category",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="provenance_details",
            field=models.TextField(default="na"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="ProvenanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(db_index=True)),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["artifact", "event_type", "date"],
                        name="artifacts_p_artifac_f77c3a_idx",
                    )
                ],
            },
        ),
    ]
