# Generated by Django 4.2.7 on 2023-11-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_artifact_aw_item_number_alter_artifact_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artifacts.county",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artifacts.region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="artifacts.state",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artifact",
            name="geography",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artifacts.geography",
            ),
        ),
    ]
