# Generated by Django 4.2.7 on 2023-11-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0006_alter_provenanceevent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="artifact",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="artifacts.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.FileField(default=None, null=True, upload_to=""),
        ),
    ]
