# .github/workflows/main.yml
# "would run command: ssh user@your-server 'export SECRET_KEY='your_secret_key' && cd /path/to/your/project && git pull origin main && ./deploy.sh'"
name: Django CI/CD
on:
  push:
    branches:
      - master
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        uses: garygrossgarten/github-action-scp@1.0

        with:
          local: test/oof.txt
          remote: scp/single/oof.txt

          password: ${{ secrets.PASSWORD }}
#          local: test/oof.txt
#          host: scp/single/oof.txt
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USER }}
          privatekey: ${{ secrets.DEPLOY_SSH_KEY }}
          command: 'ls && pwd && echo hello world'

  build:
    runs-on: ubuntu-latest
    needs: test_ssh

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py dummy 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        uses: tiyee/action-ssh@release

        with:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_PORT: 22
          SSH_REMOTE_COMMANDS: ls -la;pwd;echo "Hello World !"

            
