# .github/workflows/main.yml

name: Django CI/CD
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: Sithi5/remote-ssh-commands-action@main
        with:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_PORT: 22
          SSH_REMOTE_COMMANDS: ls -la;pwd;echo "Hello World ! here's a secret ${{ secrets.SECRET_KEY }}"
          run: |
            echo "would run command: ssh user@your-server 'export SECRET_KEY='your_secret_key' && cd /path/to/your/project && git pull origin main && ./deploy.sh'"
            
