# .github/workflows/main.yml
# "would run command: ssh user@your-server 'export SECRET_KEY='your_secret_key' && cd /path/to/your/project && git pull origin main && ./deploy.sh'"
name: Django CI/CD
on:
  push:
    branches:
      - master
jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          ${{ secrets.SSH_CMD }}
          echo "Deployment completed."
  #      - name: Testing
  #        uses: appleboy/ssh-action@master
  #        with:
  #          host: ${{ secrets.DEPLOY_SSH_HOST }}
  #          username: ${{ secrets.DEPLOY_SSH_USER }}
  #          key: ${{ secrets.NEW_SSH_KEY }}
  #          script: 'whoami && ls && pwd && echo hello world'

  build:
    runs-on: ubuntu-latest
    needs: test_ssh

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py dummy 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        uses: tiyee/action-ssh@release

        with:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_PORT: 22
          SSH_REMOTE_COMMANDS: ls -la;pwd;echo "Hello World !"

            
